export const ProjectsData = {
  categories: ["Mobile", "Web", "CLI", "Extension"],
  projects: [
    {
      title: "Maupergi",
      type: "internship",
      tech_stack: ["Flutter", "GetX", "Firebase"],
      category: "Mobile",
      description: [
        "Implemented full dark mode support across the application.",
        "Performed large-scale refactoring to improve maintainability and readability.",
        "Resolved major authentication issues and integrated Google sign-in.",
        "Fixed various minor bugs to enhance stability and UX.",
      ],
      link: "",
      repo: "",
      image: "src/assets/mobile/maupergi.webp",
    },
    {
      title: "IT Feedback",
      tech_stack: ["Flutter", "BLoC", "Firebase"],
      category: "Mobile",
      description: [
        "Built feedback/survey flow with BLoC for predictable state management.",
        "Integrated Firebase Auth (only student Accounts) for user authentication.",
      ],
      link: "",
      repo: "https://github.com/humamafif/survey-app-flutter.git",
      image: "src/assets/mobile/survey.webp",
    },
    {
      title: "Car Showroom",
      tech_stack: ["Flutter", "BLoC", "Express Js"],
      category: "Mobile",
      description: [
        "Developed car catalog UI with filtering, search, and details view.",
        "Consumed Express.js API for listing, auth, and user actions.",
        "Applied BLoC for scalable and testable presentation layer.",
      ],
      link: "",
      repo: "https://github.com/humamafif/showroom-app.git",
      image: "src/assets/mobile/showroom.webp",
    },
    {
      title: "Movies App",
      tech_stack: ["Flutter"],
      category: "Mobile",
      description: [
        "Simple TMDB client: list, search, and movie details pages.",
      ],
      link: "",
      repo: "https://github.com/humamafif/tmdb-simple-movie-app.git",
      image: "src/assets/mobile/movies.webp",
    },
    {
      title: "Cari Jasa",
      type: "internship",
      tech_stack: ["Laravel", "React", "Tailwind"],
      category: "Web",
      description: [
        "Service marketplace with public search, provider onboarding, and admin panel.",
        "Implemented authentication, category management, and responsive UI.",
      ],
      link: "",
      repo: "",
      image: "src/assets/web/cari_jasa.webp",
    },
    {
      title: "Mayar Clone",
      tech_stack: ["Laravel", "React", "Tailwind"],
      category: "Web",
      description: [
        "Final Project at Bootcamp Laravel 12 + React JS.",
        "Built a web-based e-commerce platform for selling digital products.",
        "Integrated payment gateway using Xendit for seamless transactions.",
        "Implemented responsive UI components, product listings, and checkout flow.",
      ],
      link: "",
      repo: "https://github.com/humamafif/mayar-clone.git",
      image: "src/assets/web/mayar_clone.webp",
    },
    {
      title: "Desa Ngadireso",
      tech_stack: ["React", "Tailwind"],
      category: "Web",
      description: [
        "Informational landing page for village profile and services.",
        "Optimized layout, typography, and accessibility for content-heavy pages.",
      ],
      link: "",
      repo: "https://github.com/humamafif/landingpage-desa-ngadireso.git",
      image: "src/assets/web/ngadireso.webp",
    },
    {
      title: "MA Manba'ul Ma'arif",
      tech_stack: ["Laravel", "React", "Tailwind"],
      type: "freelance",
      category: "Web",
      description: [
        "Developed the client-facing frontend for a school website as a freelance project.",
        "Built responsive pages, reusable UI components, and ensured compatibility across devices.",
        "Collaborated with backend developers to integrate dynamic content and announcements.",
      ],
      link: "",
      repo: "",
      image: "src/assets/web/manbaul_maarif.webp",
    },
    {
      title: "KoperasiKita",
      tech_stack: ["Laravel", "Filament"],
      category: "Web",
      description: [
        "Member management with role-based access control for secure operations.",
        "Automated SHU (Sisa Hasil Usaha) calculations with dynamic reporting.",
        "Product sales and inventory tracking integrated into the dashboard.",
        "Customizable resource management with Filament for rapid CRUD and relations.",
      ],
      link: "",
      repo: "https://github.com/humamafif/koperasi_kita.git",
      image: "src/assets/web/koperasi.webp",
    },
    {
      title: "Prettier Config",
      tech_stack: ["Javascript"],
      category: "CLI",
      description: [
        "CLI to bootstrap Prettier config and VSCode settings for teams.",
        "Supports revert operation and safe config generation.",
      ],
      link: "https://www.npmjs.com/package/create-prettier-config",
      repo: "https://github.com/humamafif/create-prettier-config.git",
      image: "src/assets/other/prettier.webp",
    },
    {
      title: "VS Code Theme",
      tech_stack: ["Javascript"],
      category: "Extension",
      description: [
        "Custom VS Code theme inspired by GitHub Dark.",
        "Published on Marketplace with installation instructions.",
      ],
      link: "https://marketplace.visualstudio.com/items?itemName=humamafif.github-theme-by-humamafif",
      repo: "https://github.com/humamafif/my-github-theme.git",
      image: "src/assets/other/theme.webp",
    },
  ],
};
